### ISSUE TITLE
WARNING[Server]: Assignment to undeclared global "player" inside a function at /opt/minetest/bin/../mods/chair_lift/chair_lift_entity.lua:84

### ISSUE THREAD

**Issue by superfloh247** [sfence/chair_lift#2]
WARNING[Server]: Assignment to undeclared global "player" inside a function at /opt/minetest/bin/../mods/chair_lift/chair_lift_entity.lua:84

chair_lift latest master as of now

player is wearing 3d armor and has a skinsdb skin set

world:
load_mod_unified_inventory = true
load_mod_tubelib2 = true
load_mod_skinsdb = true
load_mod_3d_armor = true
load_mod_mesecons_pistons = true
load_mod_technic = true
load_mod_mesecons_switch = true
load_mod_pipeworks = true
load_mod_moreores = true
load_mod_mesecons_wires = true
load_mod_technic_worldgen = true
load_mod_mesecons_powerplant = true
load_mod_mesecons_mvps = true
load_mod_mesecons_insulated = true
load_mod_mesecons_detector = true
load_mod_mesecons_delayer = true
load_mod_3d_armor_ui = true
load_mod_mesecons_button = true
load_mod_mesecons_materials = true
load_mod_farming = true
load_mod_mesecons_blinkyplant = true
load_mod_3d_armor_stand = true
load_mod_mesecons = true
load_mod_biofuel = true
load_mod_mesecons_receiver = true
load_mod_chair_lift = true
load_mod_basic_materials = true
load_mod_unified_inventory_plus = true
load_mod_mesecons_walllever = true
load_mod_mesecons_lamp = true
load_mod_appliances = true
load_mod_orbs_of_time = true
load_mod_mesecons_lightstone = true
load_mod_power_generators = true
load_mod_replacer = true

**Comment by sfence** [comment]
Fixed by commit [60e9e70](https://github.com/sfence/chair_lift/commit/60e9e70c3d72c957ff4d135b7641bb27b8bbf0e5)
